Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - spec/*

Metrics/ModuleLength:
  Exclude:
    - lib/cloudflare_localizable/country_list.rb

Style/ExpandPathArguments:
  Enabled: false
